"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['server.py']
DATA_FILES = ['static', 'locale','templates']
OPTIONS = {'argv_emulation': True,
	'includes' : [
		'HTMLParser',
		],
	'packages' : ["django","Libreosteo", "libreosteoweb","rest_framework",
					"haystack","sqlite3","statici18n", "email"
					],
	'plist' : {
		'LSBackgroundOnly' : True,
		'CFBundleIdentifier' : 'org.libreosteo.macos.libreosteo',
		'CFBundleGetInfoString' : 'Libreosteo',
		'CFBundleDisplayName' : 'Libreosteo',
		'CFBundleName' : 'Libreosteo',
		'CFBundleShortVersionString' : '0.2',
		'CFBundleVersion' : '0.2',
				
			},
	'extra_scripts': ['manage.py'],
	'optimize' : True,
	'iconfile' : 'libreosteoweb/static/images/favicon.icns',
		
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
