# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0031_paimentmean'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapeutsettings',
            name='last_events_enabled',
            field=models.BooleanField(default=True, verbose_name='Events history'),
        ),
        migrations.AddField(
            model_name='therapeutsettings',
            name='stats_enabled',
            field=models.BooleanField(default=True, verbose_name='Statistics'),
        ),
    ]
