# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0032_auto_20180302_1348'),
        ('libreosteoweb', '0032_auto_20180301_1244'),
    ]

    operations = [
    ]
