# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0033_merge_20180302_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapeutsettings',
            name='spheres_enabled',
            field=models.BooleanField(default=True, verbose_name='Spheres'),
        ),
    ]
