# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 11:33
from __future__ import unicode_literals

from django.db import migrations, models

def update_invoice_status(apps, schema_editor):
    Invoice = apps.get_model('libreosteoweb', 'Invoice')
    for invoice in Invoice.objects.all():
        try :
            invoice.status = invoice.examination.status 
            invoice.therapeut_id = invoice.examination.therapeut.id
            invoice.save()
        except:
            pass



class Migration(migrations.Migration):
    dependencies = [
        ('libreosteoweb', '0033_merge_20180302_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(default=0, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='therapeut_id',
            field=models.IntegerField(default=0, verbose_name='therapeut_id')
            ),
    	migrations.RunPython(update_invoice_status),

    ]
