# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0034_therapeutsettings_spheres_enabled'),
        ('libreosteoweb', '0037_auto_20190506_1653'),
    ]

    operations = [
    ]
