# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 14:54
from __future__ import unicode_literals

from django.db import migrations

def initialize_invoicing_sequence(apps, schema_editor):
    Invoice = apps.get_model('libreosteoweb', 'Invoice')
    OfficeSettings = apps.get_model('libreosteoweb', 'OfficeSettings')
    if Invoice.objects.all().count() > 0 :
        settings = OfficeSettings.objects.first()
        settings.invoice_start_sequence = u'%d' % (int(Invoice.objects.latest('date').number) + 1)
        settings.save()

class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0037_auto_20190506_1653'),
    ]

    operations = [
        migrations.RunPython(initialize_invoicing_sequence),
    ]
