# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-09 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0038_init_invoicing_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('currency', models.CharField(max_length=10, verbose_name='Currency')),
                ('paiment_mode', models.CharField(max_length=10, verbose_name='Paiment mode')),
                ('invoice', models.ManyToManyField(blank=True, to='libreosteoweb.Invoice', verbose_name='Invoices')),
            ],
        ),
    ]
