# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-11 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0038_init_invoicing_sequence'),
        ('libreosteoweb', '0038_merge_20190710_1516'),
    ]

    operations = [
    ]
