# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-30 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0040_paiment_date'),
        ('libreosteoweb', '0039_merge_20190711_1010'),
    ]

    operations = [
    ]
