# Generated by Django 2.2 on 2020-08-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0041_merge_20191030_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreosteoweb.Patient', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libreosteoweb.Invoice', verbose_name='Canceled by'),
        ),
    ]
