# Generated by Django 2.2 on 2020-08-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0041_merge_20191030_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='check_sum',
            field=models.BinaryField(default=b'', max_length=256, verbose_name='check_sum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='officesettings_id',
            field=models.IntegerField(default=1, verbose_name='office id'),
        ),
        migrations.AlterField(
            model_name='children',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreosteoweb.Patient', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libreosteoweb.Invoice', verbose_name='Canceled by'),
        ),
    ]
