# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-18 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0041_merge_20191030_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapeutsettings',
            name='zipcode_completion_enabled',
            field=models.BooleanField(default=True, verbose_name='Zipcode completion (France)'),
        ),
    ]
