# Generated by Django 2.2 on 2020-08-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0042_therapeutsettings_zipcode_completion_enabled'),
        ('libreosteoweb', '0042_auto_20200812_1526'),
    ]

    operations = [
    ]
