# Generated by Django 2.2 on 2020-08-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0043_merge_20200813_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreosteoweb.OfficeSettings', verbose_name='Office Settings'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='check_sum',
            field=models.BinaryField(default=b'', max_length=256, verbose_name='check_sum'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='officesettings_id',
            field=models.IntegerField(default=1, verbose_name='office id'),
        ),
        migrations.AddField(
            model_name='officesettings',
            name='invoice_prefix_sequence',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Invoice prefix sequence'),
        ),
        migrations.AddField(
            model_name='officesettings',
            name='office_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Office name'),
        ),
    ]
