# Generated by Django 2.2 on 2020-08-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0043_auto_20200805_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesettings',
            name='invoice_prefix_sequence',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Invoice prefix sequence'),
        ),
    ]
