# Generated by Django 2.2 on 2021-02-15 16:15

from django.db import migrations
import protected_media.models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0044_auto_20200815_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=protected_media.models.ProtectedFileField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='fileimport',
            name='file_examination',
            field=protected_media.models.ProtectedFileField(blank=True, storage=protected_media.models.ProtectedFileSystemStorage(), upload_to='tmp/'),
        ),
        migrations.AlterField(
            model_name='fileimport',
            name='file_patient',
            field=protected_media.models.ProtectedFileField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to='tmp/'),
        ),
    ]
