# Generated by Django 2.2 on 2020-08-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0044_auto_20200814_1147'),
        ('libreosteoweb', '0043_auto_20200805_1523'),
    ]

    operations = [
    ]
