# Generated by Django 2.2 on 2021-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0045_auto_20210215_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesettings',
            name='cancel_invoice_credit_note',
            field=models.BooleanField(default=True, verbose_name='Invoice canceling by credit note'),
        ),
    ]
