# Generated by Django 2.2 on 2021-03-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0047_invoice_replace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('patient.data_dump', 'Can dump data from patient')]},
        ),
    ]
