# Generated by Django 2.2 on 2021-04-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0049_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consent',
            field=models.DateField(null=True, verbose_name='Date of consent'),
        ),
    ]
