# Generated by Django 2.2.28 on 2023-12-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0050_patient_consent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='adeli',
            new_name='professional_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='professional_id_label',
            field=models.TextField(default='Adeli',
                                   verbose_name='Professional id label'),
        ),
        migrations.AddField(
            model_name='officesettings',
            name='professional_id_label',
            field=models.CharField(default='Adeli',
                                   max_length=250,
                                   verbose_name='Professional id label'),
        ),
        migrations.RenameField(
            model_name='therapeutsettings',
            old_name='adeli',
            new_name='professional_id',
        ),
    ]
