# Generated by Django 2.2.28 on 2023-12-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0051_auto_20231206_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='professional_id',
            field=models.TextField(verbose_name='Professional id'),
        ),
        migrations.AlterField(
            model_name='therapeutsettings',
            name='professional_id',
            field=models.TextField(blank=True, verbose_name='Professional id'),
        ),
    ]
