# Generated by Django 2.2.28 on 2024-04-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0052_auto_20231209_0711'),
    ]

    operations = [
        migrations.RenameField(model_name='invoice',
                               old_name='office_siret',
                               new_name='office_identifier'),
        migrations.RenameField(model_name='officesettings',
                               old_name='office_siret',
                               new_name='office_identifier'),
        migrations.RenameField(model_name='therapeutsettings',
                               old_name='siret',
                               new_name='office_identifier'),
        migrations.AddField(
            model_name='invoice',
            name='office_identifier_label',
            field=models.TextField(default='SIRET',
                                   verbose_name='Office identifier label'),
        ),
        migrations.AddField(
            model_name='officesettings',
            name='office_identifier_label',
            field=models.CharField(default='SIRET',
                                   max_length=50,
                                   verbose_name='Office identifier label'),
            preserve_default=False,
        ),
    ]
