# Generated by Django 2.2.28 on 2024-04-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0053_auto_20240426_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='office_identifier',
            field=models.TextField(blank=True, verbose_name='Office identifier'),
        ),
        migrations.AlterField(
            model_name='officesettings',
            name='office_identifier',
            field=models.CharField(max_length=50, verbose_name='Office identifier'),
        ),
        migrations.AlterField(
            model_name='officesettings',
            name='office_identifier_label',
            field=models.CharField(default='SIRET', max_length=50, verbose_name='Office identifier label'),
        ),
        migrations.AlterField(
            model_name='therapeutsettings',
            name='office_identifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Office identifier'),
        ),
    ]
