# Generated by Django 4.2.28 on 2026-06-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0054_auto_20240426_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='job',
            field=models.TextField(blank=True, default='', verbose_name='Job'),
        ),
    ]
