# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-13 14:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipcodeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(db_index=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Does not look like a french zipcode', regex='\\d{5}')])),
                ('city', models.CharField(db_index=True, max_length=60)),
            ],
        ),
    ]
