#!/bin/bash

CONFIG_DIR=etc/libreosteo
LIB_DIR=var/lib/libreosteo

source $CONFIG_DIR/settings.sh

source $LIB_DIR/check
source $LIB_DIR/install
source $LIB_DIR/remove
source $LIB_DIR/update
source $LIB_DIR/list
source $LIB_DIR/launch
source $LIB_DIR/help

$1 $@
